main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from api.models import MovieResource
from . import settings, views

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
]

admin.site.site_header = settings.ADMIN_SITE_TEXT['header']
admin.site.index_title = settings.ADMIN_SITE_TEXT['index_title']
admin.site.site_title = settings.ADMIN_SITE_TEXT['site_title']

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        resource_name = 'movies'
        queryset = Movie.objects.all()
        excludes = ['date_created']

movies/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rental_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE) # delete all movies from the genre if it's deleted
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie


# Create your views here.
def index(request):
    movies = Movie.objects.all()

    # make sure the template exists in the relevant namespace by prefixing
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)

    return render(request, 'movies/detail.html', {'movie': movie})

main/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>HerokuFlix</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">HerokuFlix</a>
    </nav>
    <main class="container">
      {% block content %}
      {% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <p>
        Welcome! Do you want to <a href="{% url 'movies:index' %}">rent movies</a> or just look around?<br/>
        To be honest, this is just a fiddling-around with Django, so <a href="https://gitlab.com/aartdb/herokuflix">you can take a look at the public repo</a> if you're interested. If not, don't take a look 👍<br/>
        You can <a href="/api/movies">take a look at the json api</a> as well!
    </p>
</div>
    <div class="fixed-bottom">
    <div class="container mb-3">
        There's not an awful lot to see here, so maybe just rent some movies?
        <div class="row">
            <div class="col-sm">
                <a href="{% url 'movies:index' %}" class="btn btn-primary d-block">rent movies</a>
            </div>
            <div class="col-sm">
                <a href="/admin" class="btn btn-secondary d-block">or take a look at the admin area</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd>{{ movie.title }}</dd>
    <dt>Genre</dt>
    <dd>{{ movie.genre }}</dd>
    <dt>Stock</dt>
    <dd>{{ movie.number_in_stock }}</dd>
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily rental rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td><a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rental_rate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}